# Generated by Django 4.2.4 on 2023-09-06 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LetsShop_App', '0003_super_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='super_sub_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LetsShop_App.super_subcategory'),
        ),
    ]
