<<<<<<< Updated upstream
# Generated by Django 4.2.4 on 2023-08-21 12:00
=======
# Generated by Django 4.2.3 on 2023-08-14 12:21
>>>>>>> Stashed changes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
